#ifndef ARCH_I386_DRIVERS_ATA_COMMON
#define ARCH_I386_DRIVERS_ATA_COMMON

#include <libds/ringbuf.h>
#include <stdint.h>
#include <stdbool.h>
#include "kernel/drivers/ata.h"
#include "../../idt/idt.h"

// Two ports, for primary and secondary channel. Use that + ATA_BUS_OFFSET_.
#define ATA_BUS_BASE_PRIMARY 0x1F0
#define ATA_BUS_BASE_SECONDARY 0x170

// (R/W) Read/write PIO data bytes
#define ATA_BUS_OFFSET_DATA 0
// (R) Errors generated by last ATA command
#define ATA_BUS_OFFSET_ERROR 1
// (W) Specific interface features
#define ATA_BUS_OFFSET_FEATURES 1
// (R/W) Number of sectors to read/write (0 is a special value)
#define ATA_BUS_OFFSET_SECTOR_COUNT 2
// (R/W) This is CHS / LBA28 / LBA48 specific.
#define ATA_BUS_OFFSET_SECTOR_NUMBER 3
// (R/W) Partial disk sector address
#define ATA_BUS_OFFSET_CYLINDER_LOW 4
// (R/W) Partial disk sector address
#define ATA_BUS_OFFSET_CYLINDER_HIGH 5
// (R/W) select device and/or head
#define ATA_BUS_OFFSET_DRIVE_HEAD 6
// (R) read current status
#define ATA_BUS_OFFSET_STATUS 7
// (W) Send ATA commands
#define ATA_BUS_OFFSET_COMMAND 7

// Commands:
#define ATA_COM_IDENTIFY 0xEC
#define ATA_COM_IDENTIFY_PACKET 0xA1
#define ATA_COM_READ_SECTORS 0x20
#define ATA_COM_WRITE_SECTORS 0x30
#define ATA_COM_FLUSH 0xE7
// Select master/slave drive
#define ATA_COM_TARGET_DRIVE_MASTER 0xA0
#define ATA_COM_TARGET_DRIVE_SLAVE 0xB0

// Status register flags:
// Indicates that an error occurred
#define ATA_STATUS_ERR 0x01
// Always set to 0
#define ATA_STATUS_IDX 0x02
// Always set to 0
#define ATA_STATUS_CORR 0x04
// has PIO data, or is ready to accept PIO data
#define ATA_STATUS_DRQ 0x08
// Overlapped Mode Service request
#define ATA_STATUS_SRV 0x10
// Drive fault error (doesn't set _ERR)
#define ATA_STATUS_DF 0x20
// Bit is clear when the drive is spun down or after an error, set otherwise
#define ATA_STATUS_RDY 0x40
// If set, drive is preparing and we need to wait. In case of hang needs reset
#define ATA_STATUS_BSY 0x80

/**
 * Type definition for a read/write request
 */
typedef struct {
    // One of ATA_DRIVE_ values from ata.h
    uint8_t drive;
    // First sector location
    uint32_t lba;
    // Total number of sectors, starting from [lba], to read/write
    uint8_t total_sectors;
    // Counts down as IRQs fire
    uint8_t remaining_sectors;
    // Caller-provider buffer, for source/destination of data
    uint16_t* buffer;
    // Is this a write request?
    bool is_write;
    // For write requests, to distinguish between "IRQ after write" and "IRQ
    // after flush".
    bool awaiting_flush;
    // Callback run when read/write is completed
    void (*callback)(void* data);
    // Data passed to [callback]
    void* callback_data;
} ata_request_t;

typedef struct __attribute__((packed)) {
    uint8_t drive_attributes;
    uint8_t chs_addr_start[3];
    uint8_t partition_type;
    uint8_t chs_addr_end[3];
    uint32_t partition_start_lba;
    uint32_t partition_sectors_count;
} ata_mbr_partition_table_entry_t;

typedef struct __attribute__((packed)) {
    uint8_t mbr_bootstrap[446];
    ata_mbr_partition_table_entry_t partition_1;
    ata_mbr_partition_table_entry_t partition_2;
    ata_mbr_partition_table_entry_t partition_3;
    ata_mbr_partition_table_entry_t partition_4;
    uint16_t signature_bytes; // 0x55 0xAA for "valid bootsector"
} ata_mbr_t;

/**
 * Selects a drive (ATA_COM_TARGET_DRIVE_) on given bus (ATA_BUS_BASE_).
 */
void _ata_drive_select(uint16_t bus_base, uint8_t drive_select);

/**
 * Returns current status byte.
 */
uint8_t _ata_read_status(uint16_t bus_base);

/**
 * Waits for BSY flag to be cleared, and returns the last status value with
 * cleared BSY.
 */
uint8_t _ata_wait_for_bsy_clear(uint16_t bus_base);

/**
 * Run device identification at init.
 */
void _ata_identify_devices();

/**
 * Enqueue a R/W request. Returns "true" when the request was accepted,
 * or "false" on error.
 */
bool _ata_enqueue_request(ata_request_t*);

/**
 * Check if there is anything in the queue, and if it is, run it. It should be
 * called in two cases:
 * 1. When there is something new added to the queue
 * 2. When the current item in the queue was finalized
 */
void _ata_queue_schedule(bool primary);

/**
 * Returns pointer to the request queue.
 */
ds_ringbuf_t* _ata_queue(bool primary);

/**
 * Run read command based on the request.
 */
void _ata_read(ata_request_t* req);

/**
 * Run write command based on the request.
 */
void _ata_write(ata_request_t* req);

/**
 * Callback function for IRQ
 */
void _ata_irq_handler(registers_t*);

/**
 * Copies partition data for later use.
 */
void _ata_save_partition_data(uint8_t drive_id, ata_mbr_t* mbr);

/**
 * Copies disk information for later uses.
 */
void _ata_save_disk_info(const uint8_t drive_id, const ata_disk_info_t* src);

#endif
