#ifndef ARCH_I386_DRIVERS_ATA_COMMON
#define ARCH_I386_DRIVERS_ATA_COMMON

#include <stdint.h>

// Two ports, for primary and secondary channel. Use that + ATA_BUS_OFFSET_.
#define ATA_BUS_BASE_PRIMARY 0x1F0
#define ATA_BUS_BASE_SECONDARY 0x170

// (R/W) Read/write PIO data bytes
#define ATA_BUS_OFFSET_DATA 0
// (R) Errors generated by last ATA command
#define ATA_BUS_OFFSET_ERROR 1
// (W) Specific interface features
#define ATA_BUS_OFFSET_FEATURES 1
// (R/W) Number of sectors to read/write (0 is a special value)
#define ATA_BUS_OFFSET_SECTOR_COUNT 2
// (R/W) This is CHS / LBA28 / LBA48 specific.
#define ATA_BUS_OFFSET_SECTOR_NUMBER 3
// (R/W) Partial disk sector address
#define ATA_BUS_OFFSET_CYLINDER_LOW 4
// (R/W) Partial disk sector address
#define ATA_BUS_OFFSET_CYLINDER_HIGH 5
// (R/W) select device and/or head
#define ATA_BUS_OFFSET_DRIVE_HEAD 6
// (R) read current status
#define ATA_BUS_OFFSET_STATUS 7
// (W) Send ATA commands
#define ATA_BUS_OFFSET_COMMAND 7

// Commands:
#define ATA_COM_IDENTIFY 0xEC
#define ATA_COM_READ_SECTORS 0x20
#define ATA_COM_WRITE_SECTORS 0x30
#define ATA_COM_FLUSH 0xE7
// Select master/slave drive
#define ATA_COM_TARGET_DRIVE_MASTER 0xA0
#define ATA_COM_TARGET_DRIVE_SLAVE 0xB0

// Status register flags:
// Indicates that an error occurred
#define ATA_STATUS_ERR 0x01
// Always set to 0
#define ATA_STATUS_IDX 0x02
// Always set to 0
#define ATA_STATUS_CORR 0x04
// has PIO data, or is ready to accept PIO data
#define ATA_STATUS_DRQ 0x08
// Overlapped Mode Service request
#define ATA_STATUS_SRV 0x10
// Drive fault error (doesn't set _ERR)
#define ATA_STATUS_DF 0x20
// Bit is clear when the drive is spun down or after an error, set otherwise
#define ATA_STATUS_RDY 0x40
// If set, drive is preparing and we need to wait. In case of hang needs reset
#define ATA_STATUS_BSY 0x80

/**
 * Selects a drive (ATA_COM_TARGET_DRIVE_) on given bus (ATA_BUS_BASE_).
 */
void _ata_drive_select(uint16_t bus_base, uint8_t drive_select);

/**
 * Returns current status byte.
 */
uint8_t _ata_read_status(uint16_t bus_base);

/**
 * Waits for BSY flag to be cleared, and returns the last status value with
 * cleared BSY.
 */
uint8_t _ata_wait_for_bsy_clear(uint16_t bus_base);

void _ata_identify_devices();

#endif
